# Generated by Django 5.1.4 on 2025-01-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='taille',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
